replicaCount: 3

image:
  repository: nginx
  tag: latest

service:
  type: ClusterIP 
  port: 80

config:
  appName: my-nginx-app
  environment: development

secret:
  username: admin
  password: admin123
